[project]
name = "bookshelf-rcmip-emissions"
version = "0.1.2a1"
description = "Emissions of greenhouse gases and air pollutants from RCMIP, for use in climate models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bookshelf[publish]==1.0.0b13",
    "pandas>=2.2",
    "scmdata>=0.16.1",
]

[tool.uv]
exclude-newer = "3 days"
exclude-newer-package = { bookshelf = false }
